### PR TITLE
Added Rubocop gem

### PR DESCRIPTION
**Pull request by wookee55**
Added Rubocop gem, a Ruby static code analyzer that enforces many of the guidelines outlined in the community Ruby Style Guide: https://github.com/bbatsov/ruby-style-guide

### CODE REVIEW

**Comment by hoitomt** [comment]
@wookee55 - did you run Rubocop on the repo? If so, it should create a file called rubocop_todo.yml. At the top of your .rubocop.yml file there will be a statement `inherit_from: .rubocop_todo.yml`. That file adds quite a few statements that actually ignore errors in the codebase. If you remove the `inherit_from .rubocop_todo.yml` statement from .rubocop.yml, It will throw likely throw a bunch of errors.

**Comment by wookee55** [comment]
@hoitomt - Added .rubocop.yml and also .rubocop_todo.yml by running rubocop --auto-gen-config

**Comment by hoitomt** [comment]
Looks good to me! We just need two +1's from the team

**Comment by AUcod3r** [comment]
+1:

**Comment by erinmadisonanthony** [comment]
:cop: :+1:

**Pull request merged**
