### PR TITLE
Added Simple Form GEM and configured

### PR DESCRIPTION
**Pull request by AUcod3r**
Added simple form support.

### CODE REVIEW

**Comment by wookee55** [comment]
:+1:

**Comment by hoitomt** [comment]
Looks good - nice work!

Next +1, please merge this one

**Comment by joehenriod** [comment]
Oh no! This one has conflicts that need to be resolved!

**Comment by AUcod3r** [comment]
Yep, this one should have been merged before devise, I will repair the conflict.  THANKS Joe!

**Pull request merged**
