### PR TITLE
Move on board

### PR DESCRIPTION
**Pull request by tiffanydarnick**

### CODE REVIEW

**Comment by hoitomt** [comment]
Looks good to me, nice work!

**Comment by erinmadisonanthony** [comment]
If we merge the code Bryan just pushed up, this method will need to be refactored because "origin" will no longer exist.

**Comment by wookee55** [comment]
do we really need to check the origin tho?

**Comment by hoitomt** [comment]
@tiffanydarnick - We can close this pull request. We actually ended up implementing the logic in each of the piece models in the `valid_moves` method. We are starting with the BOARD array when collecting the valid_moves therefore we can't end up with a point that is not on the board.

**Pull request closed without merging**
