### PR TITLE
corrected pawn logic

### PR DESCRIPTION
**Pull request by erinmadisonanthony**
Corrected an error in the pawn logic that was allowing pawns to move like knights (one over and two up, etc.)

### CODE REVIEW

**Comment by wookee55** [comment]
Get this error when I tried to run the code locally:
NameError (undefined local variable or method `coordinate' for #<Pawn:0xb53d533c>):

**Comment by erinmadisonanthony** [comment]
I switched the first part of the coordinate mapping code back to the original variation we were using. Bryan- Did this fix the error you were seeing? If not, could you try running the code the same way for one of the other models to make sure that what's happening is unique to the pawn model?

**Comment by wookee55** [comment]
it works now! seems like the code is checking for the same condition in multiple places, i consolidated the checks so the code is a bit cleaner.

**Comment by wookee55** [comment]
:+1:

**Pull request merged**
