### PR TITLE
Added Devise GEM and configured

### PR DESCRIPTION
**Pull request by AUcod3r**
We will need to go back and do some configuration mentioned here:
 1. **NOT COMPLETED FOR PRODUCTION - I added a comment for it though within the production.db file:

Ensure you have defined default url options in your environments files. Here
     is an example of default_url_options appropriate for a development environment
     in config/environments/development.rb:

       config.action_mailer.default_url_options = { :host => 'localhost:3000' }

     In production, :host should be set to the actual host of your application.

  2. *** NOT COMPLETED - we have no controllers and I didn't want to jump the gun:
Ensure you have defined root_url to *something* in your config/routes.rb.
     For example:

       root :to => "home#index"

  3. *** COMPLETED and already added Bootstrap classes in anticipation ****

Ensure you have flash messages in app/views/layouts/application.html.erb.
     For example:

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

  4. **** NOT NEEDED **** If you are deploying on Heroku with Rails 3.2 only, you may want to set:

       config.assets.initialize_on_precompile = false

     On config/application.rb forcing your application to not access the DB
     or load models when precompiling your assets.

  5. *** COMPLETED*** You can copy Devise views (for customization) to your app by running:

       rails g devise:views

### CODE REVIEW

**Comment by hoitomt** [comment]
Looks good to me. Make sure we get two +1's from the team before merging

**Comment by AUcod3r** [comment]
Mike, just to clarify, the second person to approve will merge this branch, right?

**Comment by hoitomt** [comment]
@AUcod3r - Yep, that is correct. 2nd +1 should also merge it

**Comment by AUcod3r** [comment]
Ok, redid devise and added the controller

**Comment by joehenriod** [comment]
Looks great to me.  I am going to merge the pull request!

**Pull request merged**
