### PR TITLE
Updated ajax request to submit piece_id, origin, and destination

### PR DESCRIPTION
**Pull request by wookee55**
Updated the ajax request after a piece is moved to submit the following data: 
 
game: {
  piece_id: 1,
   origin: {x: xPos, y: yPos},
   destination: {x: xPos, y: yPos},
 }

The game_id should be available by default. Note the the piece_id will always be 1 as I have yet to update the game edit view to populate the piece using the piece data, but this should be enough to get you started. I will update the game edit view in the evening.

### CODE REVIEW

**Comment by erinmadisonanthony** [comment]
Hey Bryan, quick question: in our database, we have the position variables titled x_position and y_position. Do we need to use these same labels in the AJAX?

**Comment by AUcod3r** [comment]
:+1:

**Comment by AUcod3r** [comment]
We good to go?  Can I merge or can someone merge?

**Comment by erinmadisonanthony** [comment]
:+1:

**Pull request merged**
