### PR TITLE
Game view

### PR DESCRIPTION
**Pull request by wookee55**
What I did:
1. Added game edit action
2. Added game update action to accept ajax requests during gameplay. The action currently only return dummy data.
3. Created game edit view. The view includes a chess board and chess pieces with basic theming and allows basic user interactions. It also submits ajax requests to the server upon user interactions. 
4. Hooked up logo and create new game links.

Note: Temporary updated the game new view to display a field for email instead of name.

### CODE REVIEW

**Comment by AUcod3r** [comment]
@wookee55 so which games controller gets pulled into this merge?  I see one with the edit action under private and one with it placed correctly.  Everything else looks good to me.  Did you write this JQuery out of your head or did you modify code?  The SVGs also, did you use Adobe Illustrator, some other graphics package or from whence did you get them?

**Comment by wookee55** [comment]
There should only be edit action in the games controller, see below:
https://github.com/weapons-of-mass-deduction/chess-app/blob/game-view/app/controllers/games_controller.rb

I'm use jQuery UI to facilitate the drag and drop, and I added additional functionalities such as basic error checking and ajax on top of that.

I found the chess pieces svg online.

**Comment by AUcod3r** [comment]
:+1:   Need one more...

**Comment by wookee55** [comment]
Thanks Randy, one more!!!

**Pull request merged**
